// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJkwElvCQiYam1vZ4FpaOVy-OjTk7GtGQ',
    appId: '1:534165239643:web:b9905b29d8e35642250c7e',
    messagingSenderId: '534165239643',
    projectId: 'hungerr-hub',
    authDomain: 'hungerr-hub.firebaseapp.com',
    storageBucket: 'hungerr-hub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7t1pq2PkqqnE7wJqWeZAlDEVeZfRf38A',
    appId: '1:534165239643:android:1afb03b991432b32250c7e',
    messagingSenderId: '534165239643',
    projectId: 'hungerr-hub',
    storageBucket: 'hungerr-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY1FPBk-dpezw7cV6p_nS-D1NWzDoeflk',
    appId: '1:534165239643:ios:009dffe6a47d3d98250c7e',
    messagingSenderId: '534165239643',
    projectId: 'hungerr-hub',
    storageBucket: 'hungerr-hub.appspot.com',
    iosBundleId: 'com.example.hungerhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY1FPBk-dpezw7cV6p_nS-D1NWzDoeflk',
    appId: '1:534165239643:ios:6dd323bd8264a62f250c7e',
    messagingSenderId: '534165239643',
    projectId: 'hungerr-hub',
    storageBucket: 'hungerr-hub.appspot.com',
    iosBundleId: 'com.example.hungerhub.RunnerTests',
  );
}
